Exchange Application/Controllers/CurrencyController.cs
using BusinessObject;
using BusinessLogic;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Exchange_Application.Controllers
{
    public class CurrencyController : Controller
    {
        // GET: Currency
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
         public ActionResult AddBillMaster(BillMasterView billMasterView)
        {
            BillMasteBL billMasteBL = new BillMasteBL();
            CustomMessage customMessage=   billMasteBL.AddBill(billMasterView);
            ViewBag.Message = customMessage.Message;


            return View("Index");
        }
    }
}

Exchange Application/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BusinessObject;
using BusinessLogic;

namespace Exchange_Application.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            
            return View();
        }
        public ActionResult Login(UserView userView)
        {
            CustomMessage customMessage = new CustomMessage();
            try
            {

                UserBL UBl = new UserBL();
                customMessage = UBl.Login(userView);
                if (customMessage.Value > 0)
                {
                    MenuBL menu = new MenuBL();
                    customMessage = menu.UserMenu(customMessage.Value);
                    
                }
                else
                {
                    return View("Index");
                }
                TempData["MSG"] = customMessage.Message;
            }
            catch(Exception ex)
            {
                TempData["MSG"] = customMessage.Message;
                return View("Index");
            }

            return RedirectToAction("DashBoard");


        }
        public ActionResult DashBoard()
        {
            return View();
        }
        public ActionResult MenuPartials()
        {
            return View();
        }

    }
}

Exchange Application/Views/Currency/Index.cshtml
@model BusinessObject.BillMasterView

@{
    Layout = "~/Views/Shared/MasterPage.cshtml";
    ViewBag.Title = "Index";
}

<head>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
</head>


@using (Html.BeginForm("AddBillMaster", "Currency", FormMethod.Post, new { onsubmit = "return GetRows();" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Add BillTranscation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.CustomerId, new { })
        @Html.HiddenFor(model => model.BillMasterId, new { })
        @Html.HiddenFor(model => model.GridRows, new { id = "HdnRows" })

        <div class="form-group">
            @Html.LabelFor(model => model.TranType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.TranType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.TranType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BillType, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillType, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.BillType, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.BillNo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillNo, new { htmlAttributes = new { @class = "form-control", @readonly = true } })
                @Html.ValidationMessageFor(model => model.BillNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.BillDate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.BillDate, new { htmlAttributes = new { @class = "form-control date" } })
                @Html.ValidationMessageFor(model => model.BillDate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CustomerName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CustomerName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CustomerName, "", new { @class = "text-danger" })
            </div>
        </div>

        <table class="table table-hover" id="grid">
            <thead>
                <tr>
                    <td>Currency Code<input class="form-control" id="Code" /></td>
                    <td>Currency<input class="form-control" id="Currency" /></td>
                    <td style="display:none"><input id="CurrencyId" /></td>
                    <td>FC Amount<input class="form-control" id="FcAmount" /></td>
                    <td>Rate<input class="form-control" id="Rate" /></td>
                    <td>LC Amount<input class="form-control" id="LcAmount" /></td>
                    <td><a onclick="AddRow()" class="btn btn-success"><i class="fa fa-plus" style="font-size: 18px;font-weight:bold;"></i></a></td>
                </tr>
            </thead>
            <tbody>
            </tbody>
        </table>


        <div class="form-group">
            @Html.LabelFor(model => model.LcAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LcAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LcAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FcAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FcAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FcAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>


<script>
    function AddRow() {
        debugger
        var Row = '<tr>';
        Row += '<td>' + $('#Code').val() + '</td>'
        Row += '<td>' + $('#Currency').val() + '</td>'
        Row += '<td style="display:none">' + $('#CurrencyId').val() + '</td>'
        Row += '<td>' + $('#FcAmount').val() + '</td>'
        Row += '<td>' + $('#Rate').val() + '</td>'
        Row += '<td>' + $('#LcAmount').val() + '</td>'
        Row += '<td><button onclick="DelRow(this)" class ="btn btn-danger"><i class="fi fi-dash-lg" style="font-size: 18px;font-weight:bold;"></button></i></td>'

        $('#grid tbody').append(Row);
    }

    function GetRows() {
        debugger;
        var Arr = [];
        $('#grid > tbody tr').each(function (index, elem) {
            var tb = {}

            tb.CurrencyId = $($(this).find('td:eq(2)')).html();
            tb.FcAmount = $($(this).find('td:eq(3)')).html();
            tb.Rate = $($(this).find('td:eq(4)')).html();
            tb.LcAmount = $($(this).find('td:eq(5)')).html();

            Arr.push(tb);

        })
        $('#HdnRows').val(JSON.stringify(Arr))
    }
</script>

<script src="~/Scripts/jquery-3.6.0.min.js"></script>
<script src="~/Scripts/jquery-3.6.0.js"></script>
<script src="~/Scripts/bootstrap.min.js"></script>
@*<script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>*@

Exchange Application/Views/Home/DashBoard.cshtml
@{
    ViewBag.Title = "DashBoard";
    Layout = "~/Views/Shared/MasterPage.cshtml";
}

<h2>DashBoard</h2>

Exchange Application/Views/Home/Index.cshtml
@model BusinessObject.UserView
@{
    Layout = null;
}

<!DOCTYPE html>

<html lang="en" class=" js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms no-csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths cssscrollbar">
<head>
    <meta http-equiv="content-type" content="text/html;charset=UTF-8"><!-- /Added by HTTrack -->

    <title>Admindek | Admin Template</title>


    <!--[if lt IE 10]>
          <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
          <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
          <![endif]-->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="Admindek Bootstrap admin template made using Bootstrap 4 and it has huge amount of ready made feature, UI components, pages which completely fulfills any dashboard needs.">
    <meta name="keywords" content="bootstrap, bootstrap admin template, admin theme, admin dashboard, dashboard template, admin template, responsive">
    <meta name="author" content="colorlib">

    <link rel="icon" href="https://colorlib.com/polygon/admindek/files/assets/images/favicon.ico" type="image/x-icon">

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Quicksand:500,700" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="~/Content/css/bootstrap.min.css">

    <link rel="stylesheet" href="~/Content/css/waves.min.css" type="text/css" media="all">
    <link rel="stylesheet" type="text/css" href="~/Content/css/feather.css">

    <link rel="stylesheet" type="text/css" href="~/Content/css/themify-icons.css">

    <link rel="stylesheet" type="text/css" href="~/Content/css/icofont.css">

    <link rel="stylesheet" type="text/css" href="~/Content/css/font-awesome.min.css">

    <link rel="stylesheet" type="text/css" href="~/Content/css/style.css">
    <link rel="stylesheet" type="text/css" href="~/Content/css/pages.css">
</head>
<body themebg-pattern="theme1">


    @using (Html.BeginForm("Login", "Home", FormMethod.Post, new { onsubmit = "" }))
    {
        @Html.AntiForgeryToken()
        <section class="login-block">

            <div class="container-fluid">
                <div class="row">
                    <div class="col-sm-12">

                        <form class="md-float-material form-material">
                            <div class="text-center">
                                @*<img src="png/logo.png" alt="logo.png">*@
                            </div>
                            <div class="auth-box card">
                                <div class="card-block">
                                    <div class="row m-b-20">
                                        <div class="col-md-12">
                                            <h3 class="text-center txt-primary">Sign In</h3>
                                        </div>
                                    </div>
                                    <div class="form-group form-primary">
                                        @*<input type="text" name="user-name" class="form-control" required="">*@
                                        @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
                                        <span class="form-bar"></span>
                                        <label class="float-label">Username</label>
                                    </div>
                                    <div class="form-group form-primary">

                                        @*<input type="password" name="password" class="form-control" required="">*@
                                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                                        <span class="form-bar"></span>
                                        <label class="float-label">Password</label>
                                    </div>
                                    <div class="row m-t-25 text-left">
                                        <div class="col-12">

                                        </div>
                                    </div>
                                    <div class="row m-t-30">
                                        <div class="col-md-12">
                                            <button type="submit" class="btn btn-primary btn-md btn-block waves-effect text-center m-b-20">LOGIN</button>
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </form>

                    </div>

                </div>

            </div>



        </section>
    }

        <!--[if lt IE 10]>
        <div class="ie-warning">
            <h1>Warning!!</h1>
            <p>You are using an outdated version of Internet Explorer, please upgrade <br/>to any of the following web browsers to access this website.</p>
            <div class="iew-container">
                <ul class="iew-download">
                    <li>
                        <a href="http://www.google.com/chrome/">
                            <img src="../files/assets/images/browser/chrome.png" alt="Chrome">
                            <div>Chrome</div>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.mozilla.org/en-US/firefox/new/">
                            <img src="../files/assets/images/browser/firefox.png" alt="Firefox">
                            <div>Firefox</div>
                        </a>
                    </li>
                    <li>
                        <a href="http://www.opera.com">
                            <img src="../files/assets/images/browser/opera.png" alt="Opera">
                            <div>Opera</div>
                        </a>
                    </li>
                    <li>
                        <a href="https://www.apple.com/safari/">
                            <img src="../files/assets/images/browser/safari.png" alt="Safari">
                            <div>Safari</div>
                        </a>
                    </li>
                    <li>
                        <a href="http://windows.microsoft.com/en-us/internet-explorer/download-ie">
                            <img src="../files/assets/images/browser/ie.png" alt="">
                            <div>IE (9 & above)</div>
                        </a>
                    </li>
                </ul>
            </div>
            <p>Sorry for the inconvenience!</p>
        </div>
        <![endif]-->


        <script type="text/javascript" async="" src="https://www.google-analytics.com/analytics.js"></script>
        <script type="text/javascript" src="~/Content/js/jquery.min.js"></script>
        <script type="text/javascript" src="~/Content/js/jquery-ui.min.js"></script>
        <script type="text/javascript" src="~/Content/js/popper.min.js"></script>
        <script type="text/javascript" src="~/Content/js/bootstrap.min.js"></script>

        <script src="~/Content/js/waves.min.js" type="text/javascript"></script>

        <script type="text/javascript" src="~/Content/js/jquery.slimscroll.js"></script>

        <script type="text/javascript" src="~/Content/js/modernizr.js"></script>
        <script type="text/javascript" src="~/Content/js/css-scrollbars.js"></script>
        <script type="text/javascript" src="~/Content/js/common-pages.js"></script>

        <script async="" src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="text/javascript"></script>
        <script type="text/javascript">
            window.dataLayer = window.dataLayer || [];
            function gtag() { dataLayer.push(arguments); }
            gtag('js', new Date());

            gtag('config', 'UA-23581568-13');</script>


        <!-- Mirrored from colorlib.com/polygon/admindek/default/auth-sign-in-social.html by HTTrack Website Copier/3.x [XR&CO'2014], Thu, 12 Dec 2019 16:08:30 GMT -->

    </body>
</html>

Exchange Application/Views/Home/MenuPartials.cshtml
@if (Session["MenuMaster"] != null)
{
    var Menus = (List<BusinessObject.MenuView>)Session["MenuMaster"];

    <ul class="pcoded-item pcoded-left-item" item-border="true" item-border-style="solid" subitem-border="false">
        @{foreach (var item in Menus.Where(s => s.ParentID == 0).GroupBy(Obj => new { Obj.id }).Distinct().ToList())
            {
                <li class="pcoded-hasmenu" dropdown-icon="style1" subitem-icon="style1">
                    <a href="javascript:void(0)" class="waves-effect waves-dark">
                        <span class="pcoded-micon">
                            <i class="feather icon-pie-chart"></i>
                        </span>
                        <span class="pcoded-mtext"> @item.FirstOrDefault().MenuName</span>
                    </a>
                    <ul class="pcoded-submenu">
                        @{foreach (var firstItem in (Menus.Where(s => s.ParentID == item.FirstOrDefault().id).ToList()))
                            {
                                <li>
                                    @if (firstItem.URL == null)
                                    {
                                        <a href="#" class="waves-effect waves-dark">
                                            <span class="pcoded-mtext"> @firstItem.MenuName</span>
                                        </a>
                                        <ul class="pcoded-submenu">
                                            @foreach (var secondItem in (Menus.Where(s => s.ParentID == firstItem.id).ToList()))
                                            {
                                                <li>
                                                    <a href="@secondItem.URL" class="waves-effect waves-dark">
                                                        <span class="pcoded-mtext"> @secondItem.MenuName</span>
                                                    </a>

                                                </li>

                                            }
                                        </ul>
                                    }
                                    else
                                    {
                                        <a href="#" class="waves-effect waves-dark">
                                            <span class="pcoded-mtext"> @firstItem.MenuName</span>
                                        </a>
                                        <ul class="pcoded-submenu">

                                            <li>
                                                <a href="@firstItem.URL" class="waves-effect waves-dark">
                                                    <span class="pcoded-mtext"> @firstItem.MenuName</span>
                                                </a>

                                            </li>


                                        </ul>
                                    }




                                </li>

                            }
                        }
                    </ul>
                </li>

            }
        }
    </ul>
}

Exchange Application/Views/Shared/MenuPartial.cshtml
@if (Session["MenuMaster"] != null)
{
    var Menus = (List<BusinessObject.MenuView>)Session["MenuMaster"];

<ul class="pcoded-item pcoded-left-item" item-border="true" item-border-style="solid" subitem-border="false">
    @{foreach (var item in Menus.Where(s => s.ParentID == 0).GroupBy(Obj => new { Obj.id }).Distinct().ToList())
        {
        <li class="pcoded-hasmenu" dropdown-icon="style1" subitem-icon="style1">
            <a href="javascript:void(0)" class="waves-effect waves-dark">
                <span class="pcoded-micon">
                    <i class="feather icon-pie-chart"></i>
                </span>
                <span class="pcoded-mtext"> @item.FirstOrDefault().MenuName</span>
            </a>
            <ul class="pcoded-submenu">
                @{foreach (var firstItem in (Menus.Where(s => s.ParentID == item.FirstOrDefault().id).ToList()))
                    {

                                <li>
                                    @if (firstItem.URL == null || firstItem.URL == "")
                                    {
                                        <a href="#" class="waves-effect waves-dark">
                                            <span class="pcoded-mtext"> @firstItem.MenuName</span>
                                        </a>
                                    }
                                    else
                                    {
                                        <a href="@firstItem.URL" class="waves-effect waves-dark">
                                            <span class="pcoded-mtext"> @firstItem.MenuName</span>
                                        </a>
                                    }

                                    <ul class="pcoded-submenu">
                                        @foreach (var secondItem in (Menus.Where(s => s.ParentID == firstItem.id).ToList()))
                                        {
                                            <li>
                                                <a href="@secondItem.URL" class="waves-effect waves-dark">
                                                    <span class="pcoded-mtext"> @secondItem.MenuName</span>
                                                </a>

                                            </li>

                                        }
                                    </ul>

                                </li>

                      
                           
                        





                    }
                }
            </ul>
        </li>

        }
    }
</ul>
}

Exchange Application/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.6.0.min.js"></script>
    <script src="~/Scripts/jquery-3.6.0.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>